### ISSUE TITLE
List of keyboard shortcuts?

### ISSUE THREAD

**Issue by davenotik** [jberg/butterchurn#10]
What are they? And, thank you from the depths of my heart and soul for this.

**Comment by jberg** [comment]
Hey Dave, you are welcome!

I need to actually add the keyboard controls somewhere, sorry for that.  Here is what they are in the meantime:

SPACE - next preset with transition
H - next preset without transition
DELETE - last preset
A - random mashup

**Comment by vesper8** [comment]
@jberg I'm trying to use these hotkeys in Webamp but they don't work? Do I need to enable hotkeys or do something in __butterchurnOptions ?

This is how I initialize Webamp

```
      this.webamp = new Webamp({
        initialTracks: this.tracks,
        initialSkin: this.initialSkin,
        availableSkins: this.skins,
        // filePickers: [dropboxFilePicker],
        enableHotkeys: true,
        __butterchurnOptions: {
          importButterchurn: () => import('butterchurn'),
          getPresets: () => {
            const presets = butterchurnPresets.getPresets();
            return Object.keys(presets).map((name) => ({
              name,
              butterchurnPresetObject: presets[name],
            }));
          },
          butterchurnOpen: true,
        },
        __initialWindowLayout: initialWindowLayout,
      });
```

thanks!

**Comment by jberg** [comment]
Hi @vesper8 ,

Are you making sure to click on the butterchurn window to ensure it has focus before trying keyboard shortcuts?  If you are, then there might be some issue with focus handling in webamp itself since it is handling the focus/keyboard controls.  You shouldn't need to pass anything special into the constructor for it to work.

**Comment by vesper8** [comment]
hrm.. actually it seems to be working now.. maybe i just didn't notice the subtle change between presets when i tried it before.. thanks for the reply!

**Comment by jberg** [comment]
awesome! glad you got it working
