### ISSUE TITLE
Could butterchurn force a rerender when the canvas size changes?

### ISSUE THREAD

**Issue by captbaritone** [jberg/butterchurn#13]
In firefox if there is a DOM update that changes the size of a canvas, Firefox does not actually change what's rendered on the screen until the next draw to the canvas. Could butterchurn subscribe to the `resize` event on the canvas and force a rerender?

To reproduce: Go to webamp.org in Firefox. Don't press play. Resize the Milkdrop window. See something like this:

<img width="1354" alt="screen shot 2018-10-14 at 8 41 55 am" src="https://user-images.githubusercontent.com/162735/46918913-04a41280-cf8d-11e8-920b-c609b1f4eb3a.png">

Note, that if Butterchurn is playing, the resizing works as expected, because renders are being forced.

**Comment by jberg** [comment]
We spoke this over on Discord. Going to have the renderer rerender itself after a call to `setRendererSize` to make sure it is the correct new size.

Also considering automatically detecting canvas resize changes

**Comment by jberg** [comment]
split out the final rendering to screen into its own method and calling it to rerender the current frame on resize: https://github.com/jberg/butterchurn/commit/8b297bda93ac1e96421e61cc1c4f4f9470474415
