### ISSUE TITLE
Create presets list

### ISSUE THREAD

**Issue by vargaradu** [jberg/butterchurn#14]
First of all, props for this great web app! I've used it in a live music situation (connected my mixer output into the microphone input of the app) and it worked great!

Question: Did you consider supporting playlists? For example, a favourites playlist. Because the default playlist is very big and visualisations tend to be very different.

Cheers and keep up the good work!

**Comment by jberg** [comment]
Thanks! Currently there isn't a way to create custom preset lists. I hadn't responded, because I had hoped this would be something that I had added, but it hasn't happened :-X

I will be working in the future to revamp how preset loading / preset packs work, but it will probably be a bit.

Thanks!
