### ISSUE TITLE
Just want to say thank you

### ISSUE THREAD

**Issue by LeFrach** [jberg/butterchurn#17]
Hi, 
I Just want to say Thank you for your "butterchurn". I use it in my personal music app, really awesome !

![image](https://user-images.githubusercontent.com/25138916/52783286-c0677280-3051-11e9-872b-da7ef99fb0f4.png)

**Comment by jberg** [comment]
Thanks so much! Really cool to see people using butterchurn on their own. Super cool looking app too!!!

Thanks!

**Comment by akaleeroy** [comment]
@LeFrach Hang on what's your player like? How do I get in touch?
