### ISSUE TITLE
I really would like to see a demo of the legacy implementation

### ISSUE THREAD

**Issue by lanmower** [jberg/butterchurn#21]
The legacy implementation works nicely on my raspberry, but its a bit slow, I would like to adjust its settings like the final implementation...

What would be even better is if the demo page would also work on my raspberry, could you create a version of that that works like the legacy page online?

**Comment by jberg** [comment]
Sorry, there is no longer any development on the legacy codebase

**Comment by lanmower** [comment]
I am not asking for development, I'm asking for a demo of it, since its the
only one that works on many of the devices this is useful on.

A demonstration using the one on the public website would suffice.
