### ISSUE TITLE
Width/Height Handling

### ISSUE THREAD

**Issue by jasonhendry** [jberg/butterchurn#22]
Hi,

Long time listener, first time caller.

Curious why the renderer [init] uses width/height (https://github.com/jberg/butterchurn/blob/793c29020b49ab7b3604adca07d2d92d5790efe1/src/rendering/renderer.js#L38 ) from opts but [setRenderSize ](https://github.com/jberg/butterchurn/blob/793c29020b49ab7b3604adca07d2d92d5790efe1/src/rendering/renderer.js#L235) is passed width/height and also opts.

Does it provide some additional flexibility in your implementation?

**Comment by jberg** [comment]
Hi, sorry for the delayed response.

I suppose that I could force the user to provide a `width`/`height` to the create method, but for simplicity have included some defaults. I don't think there is a particularly "good' reason.

Thanks
