### ISSUE TITLE
Is there any way to limit fps?

### ISSUE THREAD

**Issue by JohnnyAtomsk** [jberg/butterchurn#24]
Hello, I have just implemented your great library to my project. Are there any possibilities to set parameters of createVisualizer method?
I had take a look to your implementation on butterchurn.viz and you have there visualizer settings (frame rate, mesh, etc...)
Thanks for reply

**Comment by jberg** [comment]
> Hello, I have just implemented your great library to my project.

Awesome!

> Is there any way to limit fps?

It is possible, but there isn't an option to pass into the visualizer for it. Since the rate of rendering is controlled by how often you call the `render` method, you can choose the desired FPS yourself by delaying calls to `render` if the time between frames hasn't been reached yet.
