### ISSUE TITLE
Possibility to not use butterchurnPresets

### ISSUE THREAD

**Issue by JohnnyAtomsk** [jberg/butterchurn#25]
Is there any possibility to not use some presets? Or it's possible to make own instance with reduced number of presets?

**Comment by jberg** [comment]
Yes, both of those things are possible.

You could continue to use the butterchurnPresets package, but then use a whitelist to only choose between the presets you like. This will be easiest, but will be loading additional files that you wont end up using.

Alternatively you can find all the presets in JSON format here: https://github.com/jberg/butterchurn-presets/tree/master/presets/converted

You could just pick which presets you like and package it yourself.
