### ISSUE TITLE
Backgroud image/ sprite?

### ISSUE THREAD

**Issue by Catsvilles** [jberg/butterchurn#28]
Hi! What do you think, would it be possible to use an image as a background? Or maybe even some short animated gif or video and then "layer" milkdrop visualization on top of it and convert it to videos. It would be really cool to create this kind of things for sharing on social networks!

**Comment by evoyy** [comment]
Why not just place two elements of same dimensions on top of each other. The bottom element contains your background image or gif, the top element is the container for butterchurn. The end user will see no difference.

**Comment by Catsvilles** [comment]
@evoyy Yeah, looks like in the end it will be done exactly this way but I just wanted to play around, in future explore the possibility of creating visualizers directly from image maybe.

**Comment by jberg** [comment]
Thanks for answering @evoyy 

@Catsvilles : what @evoyy  said is really the only way to do it at the moment. The original MilkDrop does have support for loading images in as custom textures, but unfortunately Butterchurn doesn't support that yet
