### ISSUE TITLE
How to handle re-sizing?

### ISSUE THREAD

**Issue by IrosTheBeggar** [jberg/butterchurn#5]
Awesome project.  I saw https://butterchurnviz.com/ a while ago and it's cool to see it's been open sourced.

I'm working on integrating butterchurn into one of my projects. It's been pretty smooth, but I noticed when I resize my screen the visualizer looks distorted.  Is there a way to update the visualizer dimensions?

**Comment by jberg** [comment]
Hi @IrosTheBeggar , thanks!

Yes, you can update the visualizer width/height like this:

`visualizer.setRendererSize(width, height)`

Thanks for checking out the project
