### ISSUE TITLE
Add mStream to the readme?

### ISSUE THREAD

**Issue by IrosTheBeggar** [jberg/butterchurn#6]
I integrated butterchurn into my own project, [mStream](https://github.com/IrosTheBeggar/mStream).   It's a self-hosted music streaming sever + webapp. Can you add it to the integrations part of the readme?

[You can see a demo here](https://darncoyotes.mstream.io/).  Just click the middle button on the bottom bar.

**Comment by jberg** [comment]
oh wow, thats super awesome! Yes, I will definitely add it to the README.

Taking a look a the demo, seems like there is still a problem with the render size.  I think you need to set the width/height directly on the canvas element, in addition to calling `setRendererSize`.  Let me know if I can help.

**Comment by IrosTheBeggar** [comment]
> Taking a look a the demo, seems like there is still a problem with the render size. I think you need to set the width/height directly on the canvas element

That was the problem.  I updated the demo site and it looks much better

**Comment by jberg** [comment]
Awesome! Looks right now.

Thanks again, I'll get the README updated later today
