### ISSUE TITLE
How can I point to an audio file?

### ISSUE THREAD

**Issue by seblavoie** [jberg/butterchurn#7]
Hi, 

I am very interested in this project and I am currently trying to play around with the code. I just feel like I am missing a part here:

```
// get audioNode from audio source or microphone

visualizer.connectAudio(audioNode);
```

How can I point to an audio file here? I found in the code that it has to do with `AudioContext` so I am here so far: 

```
// get audioNode from audio source or microphone
let audioContext = new AudioContext();
let audioNode = audioContext.createBufferSource()
visualizer.connectAudio(audioNode);
```

I am bit lost from here. Thanks.

**Comment by seblavoie** [comment]
Okay I finally figured out it was more complicated by looking at demo.html.

**Comment by jberg** [comment]
Hi @seblavoie , Glad you were able to get it figured out.  Sorry for the lack of any real docs, plan on trying to fix that soon.

Thanks for checking out the project!

**Comment by SamuelGaona** [comment]
> soon

**Comment by adammpkins** [comment]
@jberg  Any hope for updated docs still?

**Comment by adammpkins** [comment]
@seblavoie Can you share what you had to do? I'll submit a pull request to the docs if I can get something working.
